name: CI

on: [pull_request]
      
jobs:

  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - uses: actions/setup-java@v1
        with:
          ruby-version: '2.6'
          java-version: 1.8
      - name: Build with Gradle
        run: 
          ./gradlew ktlintCheck
          ./gradlew tests
      - uses: MeilCli/danger-action@v2
        with:
          plugins_file: 'Gemfile'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
